// client/lib/templates/configs/clean-minimal-1x1.ts
import type { TemplateConfig } from "@/lib/templates/types";

export const cleanMinimal1x1: TemplateConfig = {
  id: "clean_minimal_01_1x1",
  format: "1x1",
  category: "showcase",
  canvas: { width: 1080, height: 1080, background: "#0F0F12" },
  layers: [
    { type: "product", x: 240, y: 80, w: 600, h: 600 },
    {
      type: "text",
      key: "headline",
      x: 80,
      y: 760,
      maxWidth: 920,
      fontSize: 64,
      fontFamily: "Noto Sans",
      fill: "#ffffff",
      fontWeight: "500",
      textAlign: "center",
    },
    {
      type: "text",
      key: "subheadline",
      x: 80,
      y: 880,
      maxWidth: 920,
      fontSize: 26,
      fontFamily: "Noto Sans",
      fill: "#a1a1aa",
      fontWeight: "400",
      textAlign: "center",
    },
    {
      type: "cta_btn",
      x: 380,
      y: 960,
      w: 320,
      h: 80,
      fill: "#ffffff",
      textFill: "#0F0F12",
      rx: 999,
    },
    {
      type: "text",
      key: "cta",
      x: 540,
      y: 1000,
      maxWidth: 320,
      fontSize: 24,
      fontFamily: "Noto Sans",
      fill: "#0F0F12",
      fontWeight: "500",
      textAlign: "center",
    },
  ],
};
