// client/lib/templates/configs/festival-bright-1x1.ts
import type { TemplateConfig } from "@/lib/templates/types";

export const festivalBright1x1: TemplateConfig = {
  id: "festival_bright_01_1x1",
  format: "1x1",
  category: "sale",
  canvas: { width: 1080, height: 1080, background: "#FF6B35" },
  layers: [
    { type: "rect", x: 0, y: 800, w: 1080, h: 280, fill: "#111111" },
    { type: "product", x: 60, y: 80, w: 520, h: 700, shadow: true },
    {
      type: "text",
      key: "headline",
      x: 620,
      y: 120,
      maxWidth: 420,
      fontSize: 56,
      fontFamily: "Noto Sans",
      fill: "#ffffff",
      fontWeight: "700",
    },
    {
      type: "text",
      key: "subheadline",
      x: 620,
      y: 320,
      maxWidth: 420,
      fontSize: 28,
      fontFamily: "Noto Sans",
      fill: "#f5e9d8",
      fontWeight: "400",
    },
    {
      type: "cta_btn",
      x: 620,
      y: 880,
      w: 360,
      h: 84,
      fill: "#ffffff",
      textFill: "#111111",
      rx: 12,
    },
    {
      type: "text",
      key: "cta",
      x: 800,
      y: 922,
      maxWidth: 360,
      fontSize: 28,
      fontFamily: "Noto Sans",
      fill: "#111111",
      fontWeight: "700",
      textAlign: "center",
    },
  ],
};
